import streamlit as st
import json
import asyncio
# This imports the new bridge function we added to your main.py
from main import run_agent_logic 

# Page Configuration
st.set_page_config(
    page_title="LedgerAI | Financial Agent",
    page_icon="💰",
    layout="centered"
)

# Sidebar for Status & Info
with st.sidebar:
    st.title("📊 System Status")
    # Updated to reflect the new self-contained architecture
    st.success("System: Online (All-in-One)")
    st.info("Environment: Hugging Face Spaces")
    st.markdown("---")
    st.markdown("### Sample Queries")
    st.code("What is the risk level for the 50k loan?")
    st.code("Summarize the ledger activities.")
    st.code("Is there any discrepancy in the GST filing?")

# Main UI
st.title("💰 LedgerAI")
st.subheader("Multi-Agent Financial Analysis System")
st.write("Upload your ledger and get AI-powered insights using Agentic RAG.")

# User Input
query = st.text_input(
    "Ask a question about your financial data:", 
    placeholder="e.g. Analyze the current debt-to-income ratio."
)

if st.button("Run Analysis"):
    if query:
        # The spinner keeps the user engaged while LangGraph works
        with st.spinner("🤖 Agents are collaborating (Planner -> Researcher -> Auditor)..."):
            try:
                # --- DIRECT EXECUTION ---
                # We call the logic directly from main.py without needing an API URL
                result = run_agent_logic(query)
                
                st.success("Analysis Complete!")
                
                # Display the Final Report from the Auditor agent
                st.markdown("### 📝 Final Report")
                st.write(result.get("output", "No report was generated by the agents."))
                
                # Display the Technical Trace (The 'How it happened')
                with st.expander("🔬 View Multi-Agent Execution Trace"):
                    st.json(result.get("full_state", {}))
                    
            except Exception as e:
                st.error(f"Execution Error: {e}")
                st.info("Ensure your API Keys are set in Hugging Face Settings -> Secrets.")
    else:
        st.warning("Please enter a question first.")

st.markdown("---")
st.caption("Developed by Ganesh | LedgerAI Finance Lab")